l = l=['BTM',
 'Banashankari',
 'Banaswadi',
 'Bannerghatta Road',
 'Basavanagudi',
 'Basaveshwara Nagar',
 'Bellandur',
 'Bommanahalli',
 'Brigade Road',
 'Brookefield',
 'CV Raman Nagar',
 'Central Bangalore',
 'Church Street',
 'City Market',
 'Commercial Street',
 'Cunningham Road',
 'Domlur',
 'East Bangalore',
 'Ejipura',
 'Electronic City',
 'Frazer Town',
 'HBR Layout',
 'HSR',
 'Hebbal',
 'Hennur',
 'Hosur Road',
 'ITPL Main Road, Whitefield',
 'Indiranagar',
 'Infantry Road',
 'JP Nagar',
 'Jakkur',
 'Jalahalli',
 'Jayanagar',
 'Jeevan Bhima Nagar',
 'KR Puram',
 'Kaggadasapura',
 'Kalyan Nagar',
 'Kammanahalli',
 'Kanakapura Road',
 'Kengeri',
 'Koramangala',
 'Koramangala 1st Block',
 'Koramangala 2nd Block',
 'Koramangala 3rd Block',
 'Koramangala 4th Block',
 'Koramangala 5th Block',
 'Koramangala 6th Block',
 'Koramangala 7th Block',
 'Koramangala 8th Block',
 'Kumaraswamy Layout',
 'Langford Town',
 'Lavelle Road',
 'MG Road',
 'Magadi Road',
 'Majestic',
 'Malleshwaram',
 'Marathahalli',
 'Mysore Road',
 'Nagarbhavi',
 'Nagawara',
 'New BEL Road',
 'North Bangalore',
 'Old Airport Road',
 'Old Madras Road',
 'Peenya',
 'RT Nagar',
 'Race Course Road',
 'Rajajinagar',
 'Rajarajeshwari Nagar',
 'Rammurthy Nagar',
 'Residency Road',
 'Richmond Road',
 'Sadashiv Nagar',
 'Sahakara Nagar',
 'Sanjay Nagar',
 'Sankey Road',
 'Sarjapur Road',
 'Seshadripuram',
 'Shanti Nagar',
 'Shivajinagar',
 'South Bangalore',
 'St. Marks Road',
 'Thippasandra',
 'Ulsoor',
 'Uttarahalli',
 'Varthur Main Road, Whitefield',
 'Vasanth Nagar',
 'Vijay Nagar',
 'West Bangalore',
 'Whitefield',
 'Wilson Garden',
 'Yelahanka',
 'Yeshwantpur']

m=['Bakery',
 'Bakery, Beverage Shop',
 'Bakery, Cafe',
 'Bakery, Dessert Parlor',
 'Bakery, Food Court',
 'Bakery, Kiosk',
 'Bakery, Quick Bites',
 'Bakery, Sweet Shop',
 'Bar',
 'Bar, Cafe',
 'Bar, Casual Dining',
 'Bar, Lounge',
 'Bar, Pub',
 'Bar, Quick Bites',
 'Beverage Shop',
 'Beverage Shop, Cafe',
 'Beverage Shop, Dessert Parlor',
 'Beverage Shop, Quick Bites',
 'Bhojanalya',
 'Cafe',
 'Cafe, Bakery',
 'Cafe, Bar',
 'Cafe, Casual Dining',
 'Cafe, Dessert Parlor',
 'Cafe, Food Court',
 'Cafe, Lounge',
 'Cafe, Quick Bites',
 'Casual Dining',
 'Casual Dining, Bar',
 'Casual Dining, Cafe',
 'Casual Dining, Irani Cafee',
 'Casual Dining, Lounge',
 'Casual Dining, Microbrewery',
 'Casual Dining, Pub',
 'Casual Dining, Quick Bites',
 'Casual Dining, Sweet Shop',
 'Club',
 'Club, Casual Dining',
 'Confectionery',
 'Delivery',
 'Dessert Parlor',
 'Dessert Parlor, Bakery',
 'Dessert Parlor, Beverage Shop',
 'Dessert Parlor, Cafe',
 'Dessert Parlor, Food Court',
 'Dessert Parlor, Kiosk',
 'Dessert Parlor, Quick Bites',
 'Dessert Parlor, Sweet Shop',
 'Dhaba',
 'Fine Dining',
 'Fine Dining, Bar',
 'Fine Dining, Lounge',
 'Fine Dining, Microbrewery',
 'Food Court',
 'Food Court, Beverage Shop',
 'Food Court, Casual Dining',
 'Food Court, Dessert Parlor',
 'Food Court, Quick Bites',
 'Food Truck',
 'Kiosk',
 'Lounge',
 'Lounge, Bar',
 'Lounge, Cafe',
 'Lounge, Casual Dining',
 'Lounge, Microbrewery',
 'Mess',
 'Mess, Quick Bites',
 'Microbrewery',
 'Microbrewery, Bar',
 'Microbrewery, Casual Dining',
 'Microbrewery, Lounge',
 'Microbrewery, Pub',
 'Pop Up',
 'Pub',
 'Pub, Bar',
 'Pub, Cafe',
 'Pub, Casual Dining',
 'Pub, Microbrewery',
 'Quick Bites',
 'Quick Bites, Bakery',
 'Quick Bites, Beverage Shop',
 'Quick Bites, Cafe',
 'Quick Bites, Dessert Parlor',
 'Quick Bites, Food Court',
 'Quick Bites, Kiosk',
 'Quick Bites, Meat Shop',
 'Quick Bites, Mess',
 'Quick Bites, Sweet Shop',
 'Sweet Shop',
 'Sweet Shop, Dessert Parlor',
 'Sweet Shop, Quick Bites',
 ]
       
 
